steps:
    - name: gcr.io/cloud-builders/docker
      args: ["build", "-t", "gcr.io/$PROJECT_ID/adk-live-bridge:latest", "."]
      dir: server

    - name: gcr.io/cloud-builders/docker
      args: ["push", "gcr.io/$PROJECT_ID/adk-live-bridge:latest"]

    - name: gcr.io/cloud-builders/gcloud
      args:
          [
              "run",
              "deploy",
              "adk-live-bridge",
              "--image",
              "gcr.io/$PROJECT_ID/adk-live-bridge:latest",
              "--region",
              "$LOCATION",
              "--platform",
              "managed",
              "--allow-unauthenticated",
          ]

images:
    - gcr.io/$PROJECT_ID/adk-live-bridge:latest

options:
    logging: CLOUD_LOGGING_ONLY
