export const APP_CONFIG = {
    NAME: "Shopping Assistant",
    VERSION: "1.0",
    DESCRIPTION: "AI-powered shopping assistant with voice and visual input",
};

export const MESSAGE_TYPES = {
    PROCESS_USER_QUERY: "PROCESS_USER_QUERY",
    REQUEST_MIC_PERMISSION: "REQUEST_MIC_PERMISSION",
    SIDE_PANEL_OPENED: "SIDE_PANEL_OPENED",
    SIDE_PANEL_CLOSED: "SIDE_PANEL_CLOSED",
    LISTENING_STOPPED: "LISTENING_STOPPED",
    CONVERSATION_UPDATED: "CONVERSATION_UPDATED",
};
