export const APP_CONFIG = {
    NAME: 'Shopping Assistant',
    VERSION: '1.0',
    DESCRIPTION: 'AI-powered shopping assistant with voice and visual input'
};

export const MESSAGE_TYPES = {
    PAGE_INFO_UPDATE: 'PAGE_INFO_UPDATE',
    PAGE_INFO_BROADCAST: 'PAGE_INFO_BROADCAST',
    GET_CURRENT_TAB_INFO: 'GET_CURRENT_TAB_INFO',
    GET_PAGE_INFO: 'GET_PAGE_INFO',
    PROCESS_USER_QUERY: 'PROCESS_USER_QUERY',
    REQUEST_MIC_PERMISSION: 'REQUEST_MIC_PERMISSION',
    SIDE_PANEL_OPENED: 'SIDE_PANEL_OPENED',
    SIDE_PANEL_CLOSED: 'SIDE_PANEL_CLOSED'
};